In [51]:
import pandas as pd  
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [52]:
df = pd.read_csv("Audi.csv")

In [53]:
df.head(3)

,index,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),href,PPY,MileageRank,PriceRank,PPYRank,Score
0,0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,https://www.autotrader.co.uk/car-details/20221...,2499.166667,215,163,340,718
1,4,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,https://www.autotrader.co.uk/car-details/20221...,2688.750000,222,330,276,828
2,7,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,https://www.autotrader.co.uk/car-details/20221...,3599.666667,221,327,94,642

In [54]:
df = df[["Year","Type","Mileage(miles)","Engine","PS","Transmission","Fuel","Number_of_Owners","Price(£)"]]

In [55]:
df.head(3)

,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£)
0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0
1,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0
2,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0

In [56]:
df.columns = ["Yıl","Araba Türü","Mil","Motor Hacmi","Beygir Gücü","Vites Türü","Yakıt Türü","Sahip Sayısı","Fiyat"]

In [57]:
df.head(3)

,Yıl,Araba Türü,Mil,Motor Hacmi,Beygir Gücü,Vites Türü,Yakıt Türü,Sahip Sayısı,Fiyat
0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0
1,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0
2,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0

In [58]:
df["Motor Hacmi"] = df["Motor Hacmi"].str.replace("L","")

In [59]:
df["Motor Hacmi"] = df["Motor Hacmi"].astype(float)

In [60]:
df = pd.get_dummies(df, columns = ["Araba Türü", "Vites Türü", "Yakıt Türü"],dtype=int, drop_first=True)

In [61]:
df.head(3)

,Yıl,Mil,Motor Hacmi,Beygir Gücü,Sahip Sayısı,Fiyat,Vites Türü_Manual,Yakıt Türü_Petrol
0,2018.0,44000.0,1.6,114.398422,1,14995.0,1,0
1,2016.0,42596.0,1.0,93.688363,3,10755.0,1,1
2,2015.0,42700.0,1.4,123.274162,2,10799.0,1,1

In [62]:
df["Yıl"] = df["Yıl"].astype("int")

In [63]:
df.head()

,Yıl,Mil,Motor Hacmi,Beygir Gücü,Sahip Sayısı,Fiyat,Vites Türü_Manual,Yakıt Türü_Petrol
0,2018,44000.0,1.6,114.398422,1,14995.0,1,0
1,2016,42596.0,1.0,93.688363,3,10755.0,1,1
2,2015,42700.0,1.4,123.274162,2,10799.0,1,1
3,2014,86000.0,1.6,103.550296,3,7490.0,1,0
4,2014,104310.0,1.6,103.550296,3,7400.0,1,0

In [64]:
y = df[["Fiyat"]]
x = df.drop("Fiyat", axis = 1)

In [68]:
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.80,random_state=22)

In [69]:
lm = LinearRegression()
model = lm.fit(x_train,y_train)
model.score(x_test,y_test)

0.9053777751951051

In [70]:
df.head(3)

,Yıl,Mil,Motor Hacmi,Beygir Gücü,Sahip Sayısı,Fiyat,Vites Türü_Manual,Yakıt Türü_Petrol
0,2018,44000.0,1.6,114.398422,1,14995.0,1,0
1,2016,42596.0,1.0,93.688363,3,10755.0,1,1
2,2015,42700.0,1.4,123.274162,2,10799.0,1,1

In [71]:
model.predict([[2016,30000,1.0,90,5,0,1]])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[13721.03952625]])