In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("Audi.csv")

In [3]:
df.head(3)

,index,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),href,PPY,MileageRank,PriceRank,PPYRank,Score
0,0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,https://www.autotrader.co.uk/car-details/20221...,2499.166667,215,163,340,718
1,4,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,https://www.autotrader.co.uk/car-details/20221...,2688.750000,222,330,276,828
2,7,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,https://www.autotrader.co.uk/car-details/20221...,3599.666667,221,327,94,642

In [4]:
df = df.drop(columns=["index","href","MileageRank","PriceRank","PPYRank","Score"])

In [5]:
df.head(3)

,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),PPY
0,2018.0,Hatchback,44000.0,1.6L,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0L,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4L,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [6]:
# regression formula : y = ax + b

In [7]:
df["Engine"] = df["Engine"].str.replace("L","")
df

,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),PPY
0,2018.0,Hatchback,44000.0,1.6,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4,123.274162,Manual,Petrol,2,10799.0,3599.666667
3,2014.0,Hatchback,86000.0,1.6,103.550296,Manual,Diesel,3,7490.0,3745.000000
4,2014.0,Hatchback,104310.0,1.6,103.550296,Manual,Diesel,3,7400.0,3700.000000
...,...,...,...,...,...,...,...,...,...,...
466,2014.0,Hatchback,40195.0,1.4,138.067061,Automatic,Petrol,3,11275.0,5637.500000
467,2020.0,Hatchback,26218.0,1.0,114.398422,Manual,Petrol,1,18495.0,2311.875000
468,2017.0,Hatchback,48571.0,1.4,123.274162,Manual,Petrol,2,11995.0,2399.000000
469,2020.0,Hatchback,9584.0,1.0,93.688363,Manual,Petrol,1,19970.0,2496.250000
470,2019.0,Hatchback,17303.0,1.0,114.398422,Manual,Petrol,1,17195.0,2456.428571

In [8]:
df["Engine"] = df["Engine"].astype(float)
df

,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),PPY
0,2018.0,Hatchback,44000.0,1.6,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4,123.274162,Manual,Petrol,2,10799.0,3599.666667
3,2014.0,Hatchback,86000.0,1.6,103.550296,Manual,Diesel,3,7490.0,3745.000000
4,2014.0,Hatchback,104310.0,1.6,103.550296,Manual,Diesel,3,7400.0,3700.000000
...,...,...,...,...,...,...,...,...,...,...
466,2014.0,Hatchback,40195.0,1.4,138.067061,Automatic,Petrol,3,11275.0,5637.500000
467,2020.0,Hatchback,26218.0,1.0,114.398422,Manual,Petrol,1,18495.0,2311.875000
468,2017.0,Hatchback,48571.0,1.4,123.274162,Manual,Petrol,2,11995.0,2399.000000
469,2020.0,Hatchback,9584.0,1.0,93.688363,Manual,Petrol,1,19970.0,2496.250000
470,2019.0,Hatchback,17303.0,1.0,114.398422,Manual,Petrol,1,17195.0,2456.428571

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 471 entries, 0 to 470
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              471 non-null    float64
 1   Type              471 non-null    object
 2   Mileage(miles)    471 non-null    float64
 3   Engine            471 non-null    float64
 4   PS                471 non-null    float64
 5   Transmission      471 non-null    object
 6   Fuel              471 non-null    object
 7   Number_of_Owners  471 non-null    int64
 8   Price(£)          471 non-null    float64
 9   PPY               471 non-null    float64
dtypes: float64(6), int64(1), object(3)
memory usage: 36.9+ KB

In [10]:
df.head(3)

,Year,Type,Mileage(miles),Engine,PS,Transmission,Fuel,Number_of_Owners,Price(£),PPY
0,2018.0,Hatchback,44000.0,1.6,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [11]:
df.columns = ["Yıl","Kasa Tipi","Mil","Motor","Beygir Gücü","Vites Türü","Yakıt Türü","Sahip Sayısı","Fiyat","PPY"]

In [12]:
df.head(3)

,Yıl,Kasa Tipi,Mil,Motor,Beygir Gücü,Vites Türü,Yakıt Türü,Sahip Sayısı,Fiyat,PPY
0,2018.0,Hatchback,44000.0,1.6,114.398422,Manual,Diesel,1,14995.0,2499.166667
1,2016.0,Hatchback,42596.0,1.0,93.688363,Manual,Petrol,3,10755.0,2688.750000
2,2015.0,Hatchback,42700.0,1.4,123.274162,Manual,Petrol,2,10799.0,3599.666667

In [13]:
df_new = df.copy()

In [14]:
df_new = pd.get_dummies(df, columns=["Kasa Tipi","Vites Türü","Yakıt Türü"], dtype=int) # Don't forget to dtype.

In [15]:
df_new

,Yıl,Mil,Motor,Beygir Gücü,Sahip Sayısı,Fiyat,PPY,Kasa Tipi_Hatchback,Vites Türü_Automatic,Vites Türü_Manual,Yakıt Türü_Diesel,Yakıt Türü_Petrol
0,2018.0,44000.0,1.6,114.398422,1,14995.0,2499.166667,1,0,1,1,0
1,2016.0,42596.0,1.0,93.688363,3,10755.0,2688.750000,1,0,1,0,1
2,2015.0,42700.0,1.4,123.274162,2,10799.0,3599.666667,1,0,1,0,1
3,2014.0,86000.0,1.6,103.550296,3,7490.0,3745.000000,1,0,1,1,0
4,2014.0,104310.0,1.6,103.550296,3,7400.0,3700.000000,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
466,2014.0,40195.0,1.4,138.067061,3,11275.0,5637.500000,1,1,0,0,1
467,2020.0,26218.0,1.0,114.398422,1,18495.0,2311.875000,1,0,1,0,1
468,2017.0,48571.0,1.4,123.274162,2,11995.0,2399.000000,1,0,1,0,1
469,2020.0,9584.0,1.0,93.688363,1,19970.0,2496.250000,1,0,1,0,1
470,2019.0,17303.0,1.0,114.398422,1,17195.0,2456.428571,1,0,1,0,1

In [16]:
df_new = pd.get_dummies(df, columns=["Kasa Tipi","Vites Türü","Yakıt Türü"], dtype=int, drop_first=True)

In [17]:
df_new

,Yıl,Mil,Motor,Beygir Gücü,Sahip Sayısı,Fiyat,PPY,Vites Türü_Manual,Yakıt Türü_Petrol
0,2018.0,44000.0,1.6,114.398422,1,14995.0,2499.166667,1,0
1,2016.0,42596.0,1.0,93.688363,3,10755.0,2688.750000,1,1
2,2015.0,42700.0,1.4,123.274162,2,10799.0,3599.666667,1,1
3,2014.0,86000.0,1.6,103.550296,3,7490.0,3745.000000,1,0
4,2014.0,104310.0,1.6,103.550296,3,7400.0,3700.000000,1,0
...,...,...,...,...,...,...,...,...,...
466,2014.0,40195.0,1.4,138.067061,3,11275.0,5637.500000,0,1
467,2020.0,26218.0,1.0,114.398422,1,18495.0,2311.875000,1,1
468,2017.0,48571.0,1.4,123.274162,2,11995.0,2399.000000,1,1
469,2020.0,9584.0,1.0,93.688363,1,19970.0,2496.250000,1,1
470,2019.0,17303.0,1.0,114.398422,1,17195.0,2456.428571,1,1

In [18]:
y = df_new[["Fiyat"]]
x = df_new.drop("Fiyat", axis  =1)

In [19]:
lm = LinearRegression()
model = lm.fit(x,y)

In [21]:
model.predict([[2017,30000,1.6,110,1,2600,0,1]])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[13145.9080419]])

In [22]:
model.score(x,y)

0.9595295772839728