In [47]:
import numpy as np
import pandas as pd 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error , mean_squared_error, mean_absolute_percentage_error
# I will start in the morning.

In [48]:
df = pd.read_csv("insurance.csv")

In [49]:
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [50]:
df = pd.get_dummies(df,columns=["sex","smoker","region"], drop_first=True, dtype = int)

In [51]:
df.head(3)

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.90,0,16884.9240,0,1,0,0,1
1,18,33.77,1,1725.5523,1,0,0,1,0
2,28,33.00,3,4449.4620,1,0,0,1,0

In [52]:
y = df[["charges"]]
x = df.drop("charges",axis=1)

In [53]:
lm = LinearRegression()
model = lm.fit(x,y)

In [54]:
model.score(x,y)

0.7509130345985207

In [55]:
model.predict([[19,26,0,1,1,0,0,1]])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[24517.93110714]])

In [56]:
model.predict([[19,27.90,0,0,1,0,0,1]])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[25293.7130284]])

In [57]:
df_hata = pd.DataFrame()

In [58]:
df_hata["y"] = y

In [59]:
df_hata

                y
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [60]:
y_tahmin = model.predict(x)

In [61]:
df_hata["y_tahmin"] = y_tahmin

In [62]:
df_hata

                y      y_tahmin
0     16884.92400  25293.713028
1      1725.55230   3448.602834
2      4449.46200   6706.988491
3     21984.47061   3754.830163
4      3866.85520   5592.493386
...           ...           ...
1333  10600.54830  12351.323686
1334   2205.98080   3511.930809
1335   1629.83350   4149.132486
1336   2007.94500   1246.584939
1337  29141.36030  37085.623268

[1338 rows x 2 columns]

In [63]:
df_hata["error"] = (y-y_tahmin)

In [64]:
df_hata.head(10)

             y      y_tahmin         error
0  16884.92400  25293.713028  -8408.789028
1   1725.55230   3448.602834  -1723.050534
2   4449.46200   6706.988491  -2257.526491
3  21984.47061   3754.830163  18229.640447
4   3866.85520   5592.493386  -1725.638186
5   3756.62160   3719.825799     36.795801
6   8240.58960  10659.961225  -2419.371625
7   7281.50560   8047.910607   -766.405007
8   6406.41070   8502.973920  -2096.563220
9  28923.13692  11884.637518  17038.499402

In [65]:
df_hata["squared_error"] = df_hata["error"] ** 2

In [66]:
df_hata["abs_error"] = np.abs(df_hata["error"])

In [67]:
df_hata.head(10)

             y      y_tahmin         error  squared_error     abs_error
0  16884.92400  25293.713028  -8408.789028   7.070773e+07   8408.789028
1   1725.55230   3448.602834  -1723.050534   2.968903e+06   1723.050534
2   4449.46200   6706.988491  -2257.526491   5.096426e+06   2257.526491
3  21984.47061   3754.830163  18229.640447   3.323198e+08  18229.640447
4   3866.85520   5592.493386  -1725.638186   2.977827e+06   1725.638186
5   3756.62160   3719.825799     36.795801   1.353931e+03     36.795801
6   8240.58960  10659.961225  -2419.371625   5.853359e+06   2419.371625
7   7281.50560   8047.910607   -766.405007   5.873766e+05    766.405007
8   6406.41070   8502.973920  -2096.563220   4.395577e+06   2096.563220
9  28923.13692  11884.637518  17038.499402   2.903105e+08  17038.499402

In [68]:
df_hata["percent_error"] = np.abs((y-y_tahmin)/y)

In [69]:
df_hata

,y,y_tahmin,error,squared_error,abs_error,percent_error
0,16884.92400,25293.713028,-8408.789028,7.070773e+07,8408.789028,0.498006
1,1725.55230,3448.602834,-1723.050534,2.968903e+06,1723.050534,0.998550
2,4449.46200,6706.988491,-2257.526491,5.096426e+06,2257.526491,0.507371
3,21984.47061,3754.830163,18229.640447,3.323198e+08,18229.640447,0.829205
4,3866.85520,5592.493386,-1725.638186,2.977827e+06,1725.638186,0.446264
...,...,...,...,...,...,...
1333,10600.54830,12351.323686,-1750.775386,3.065214e+06,1750.775386,0.165159
1334,2205.98080,3511.930809,-1305.950009,1.705505e+06,1305.950009,0.592004
1335,1629.83350,4149.132486,-2519.298986,6.346867e+06,2519.298986,1.545740
1336,2007.94500,1246.584939,761.360061,5.796691e+05,761.360061,0.379174
1337,29141.36030,37085.623268,-7944.262968,6.311131e+07,7944.262968,0.272611

In [70]:
df_hata.mean()

y                1.327042e+04
y_tahmin         1.327042e+04
error            3.072434e-12
squared_error    3.650189e+07
abs_error        4.170887e+03
percent_error    4.203527e-01
dtype: float64

In [71]:
mean_squared_error(y,y_tahmin)

36501893.00741544

In [72]:
mean_absolute_error(y,y_tahmin)

4170.886894163586

In [73]:
mean_absolute_percentage_error(y,y_tahmin)

0.42035268473727017