In [2]:
from sklearn.linear_model import LinearRegression
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv("Student_Marks.csv")

In [5]:
df.head(3)

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811

In [6]:
df.columns = ["sınıf", "saat", "puan"]

In [7]:
df.head(3)

   sınıf   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [8]:
y = df[["puan"]]
x = df[["sınıf","saat"]]

In [10]:
lm = LinearRegression()
model = lm.fit(x,y)

In [11]:
# y = ax + b

In [ ]:
model.coef_ # katsayı

array([[1.86405074, 5.39917879]])

In [14]:
model.intercept_ # sabit

array([-7.45634623])

In [16]:
model.predict([[4,5]])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[26.99575068]])

In [19]:
(4 * 1.86405074) + (5 * 5.39917879) -7.45634623 # proof of predict calculation

26.99575068

In [20]:
df.head(3)

   sınıf   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [21]:
s1 = model.predict([[3,4.508]])
s1

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[22.47530397]])

In [26]:
abs(19.202 - s1) / 19.202  # %17'lik bir sapma olduğunu gördük, ve abs fonksiyonunu koyarak mutlak değerini aldım.

array([[0.17046682]])

In [29]:
model.score(x,y) # %6'lık sapma genel anlamda olduğunu gördük.

0.9403656320238896